### ISSUE TITLE
Removing tag on asana side causes error (SEE BELOW)

### ISSUE THREAD

**Issue by robertDurst** [not-Stellar/github-asana#68]
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubRepoName' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:280:48)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'githubID' of null
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:275:31)
    at <anonymous>
TypeError: Cannot read property 'id' of undefined
    at eventInfo.forEach (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:266:62)
    at Array.forEach (<anonymous>)
    at Object.asanaToGithub (/Users/ps1/Desktop/github-asana/lib/bridge/bridge.js:263:13)

**Comment by robertDurst** [comment]
EHHH not important
